/*
This program calls parse() in packetread.c & reads the intermediate file "ic.txt". It then generates DETAILED OUTPUT in human readable format along with the SUMMARY of the input file.
Input : 1st parameter = PCAP test file, 2nd parameter = output file name for info generated
Output : {argv[2]}.txt i.e output file that contains all the DETAILED FIELDS and SUMMARY at the end.
*/

#include<stdio.h>
#include<string.h>
#include "packetread.c"
#define MAX 65535
#define line fprintf(fp_info, "-------------------------------------------------------------------------------------\n");

void print_ip_header(char**, FILE*, int, int);
void print_tcp_header(char**, FILE*);
void print_time(char**, FILE*, int);
void print_summary(int, FILE*, char[]);
void print_packet_data(char**, FILE*, int);
int total_size=0;
	
int main(int argc, char **argv)	//1st parameter = PCAP test file, 2nd parameter = output file name for info generated
{
	FILE *fp_ic, *fp_info;
	char packet_buffer[MAX]; //buffer to store info of one complete packet at packet_buffer time
	char* tokens[MAX/2], *ptr; //buffer to store tokens of single packet; ptr is iterator for same task
	int toknum, i, d, errno;
	unsigned long total_bytes=0; //total number of bytes in a session
	extern unsigned long sec_diff; //extreme time difference in a session file

	errno = parse(argv[1]); //function parses the pcap file and converts the dump into hexadecimal form
	if(errno == 1)
		printf("\nError opening the input PCAP file.");
	else if(errno == 2)
		printf("\nError opening new file for intermediate code generation.");

	fp_ic = fopen("ic.txt", "r"); //open the IC file generated by parse() function	
	fp_info = fopen(argv[2], "w+"); //open the output file to write PCAP analysis 

	fprintf(fp_info, "\n|****************************************************************************************************|\n|*																									*|\n|*					SUMMARY FOR THIS FILE IS AT THE END OF THIS TEXT FILE							*|\n|*																									*|\n|****************************************************************************************************|\n\n");
	for (i=0; fgets(packet_buffer, sizeof(packet_buffer), fp_ic)!=NULL; i++) //process one packet at a time
	{
		toknum=0;
		{
			d = strlen(packet_buffer);
			for(ptr = strtok(packet_buffer," "); ptr!=NULL; ptr = strtok(NULL, " \n")) //tokenize packet info
			{
 				tokens[toknum] = ptr;
				toknum++;
			}
			print_ip_header(tokens, fp_info, i, toknum); //print ip header info in output file
			print_tcp_header(tokens, fp_info); //print tcp header in output file
			print_packet_data(tokens, fp_info, toknum); //print the data in the packet
			fprintf(fp_info, "\n\n");
		}
	}
	print_summary(i, fp_info, argv[1]); //print overall session summary
	return 0;
}

void print_ip_header(char** tokens, FILE* fp_info, int k, int toknum)
{
	//used to print IP Header info 
	//input : tokens in hex form obtained from dump file
	//output : IP header info like packet no, src, dest addresses, TTL, header length, total packet length, etc. 
	char temp[50], words[2], word_size[2];
	int i, header_size;
	line

	fprintf(fp_info, "\nPacket Number: %d\n", k+1);

	if(!strcmp(tokens[12], "08") && !strcmp(tokens[13], "00"))
		fprintf(fp_info, "\nPacket Type \t\t\t\t\tIP (Internet Layer)");
	else if(!strcmp(tokens[12], "08") && !strcmp(tokens[13], "06"))
		fprintf(fp_info, "\nPacket Type \t\t\t\t\tARP");

	print_time(tokens, fp_info, toknum);	//print Timestamp
	
	fprintf(fp_info, "\nEthernet SRC Address \t\t\t");
	for(i=0; i<5; i++)	
		fprintf(fp_info, "%s:", tokens[i]);
	fprintf(fp_info, "%s", tokens[5]);

	fprintf(fp_info, "\nEthernet DEST Address \t\t\t");
	for(i=6; i<11; i++)	
		fprintf(fp_info, "%s:", tokens[i]);
	fprintf(fp_info, "%s", tokens[11]);

	word_size[0] = tokens[14][0];
	word_size[1]='\0';
	words[0] = tokens[14][1];
	words[1] ='\0';
	header_size = (int)strtol(word_size, NULL, 16)*(int)strtol(words, NULL, 16);

	fprintf(fp_info, "\nIP Header Length \t\t\t\t%d Bytes", header_size);
	
	strcat(temp, tokens[16]);
	strcat(temp, tokens[17]);
	fprintf(fp_info, "\nTotal Length \t\t\t\t\t%d Bytes", (int)strtol(temp, NULL, 16));
	total_size += (int)strtol(temp, NULL, 16);

	fprintf(fp_info, "\nTTL \t\t\t\t\t\t\t%d", (int)strtol(tokens[22], NULL, 16));

	fprintf(fp_info, "\nSRC IP Address \t\t\t\t\t");
	for(i=26; i<29; i++)	
		fprintf(fp_info, "%d.", (int)strtol(tokens[i], NULL, 16));
	fprintf(fp_info, "%d", (int)strtol(tokens[29], NULL, 16));
	
	fprintf(fp_info, "\nDEST IP Address \t\t\t\t");
	for(i=30; i<33; i++)	
		fprintf(fp_info, "%d.", (int)strtol(tokens[i], NULL, 16));
	fprintf(fp_info, "%d", (int)strtol(tokens[33], NULL, 16));
}

void print_tcp_header(char** tokens, FILE* fp_info)
{
	//used to print TCP Header info 
	//input : tokens in hex form obtained from dump file
	//output : TCP header info like src, dest port no., header length, window size, etc. 

	char temp1[50]="", temp2[50]="", temp3[50]="", temp0[2];

	temp0[0] = tokens[46][0];
	temp0[1] = '\0';
	fprintf(fp_info, "\n\nTCP Header Length \t\t\t\t%d", (int)strtol(temp0, NULL, 16)*4);

	strcat(temp1, tokens[34]);
	strcat(temp1, tokens[35]);
	fprintf(fp_info, "\nTCP SRC Port \t\t\t\t\t%d", (int)strtol(temp1, NULL, 16));
	
	strcat(temp2, tokens[36]);
	strcat(temp2, tokens[37]);
	fprintf(fp_info, "\nTCP DEST Port \t\t\t\t\t%d", (int)strtol(temp2, NULL, 16));

	strcat(temp3, tokens[48]);
	strcat(temp3, tokens[49]);
	fprintf(fp_info, "\nWindow Size \t\t\t\t\t%d", (int)strtol(temp3, NULL, 16));
}

void print_time(char** tokens, FILE* fp_info, int toknum)
{
	//used to print PCAP file summary 
	//input : total number of packets
	//output : many summary stats like avg packet size, transfer speed, etc 
	fprintf(fp_info, "\nTimestamp (of Packet Capture)\t%s T %s GMT", tokens[toknum-2], tokens[toknum-1]);
}

void print_packet_data(char** tokens, FILE* fp_info, int toknum)
{
	//used to print PCAP packet data 
	//input : total number of packets, tokens
	//output : actual data present in the packets 
	int i, invalidchar_flag=1, ch;
	char n;

	fprintf(fp_info, "\n\nData in packet: ");
	for(i=54; i<toknum-3; i++)
	{
		ch = (int)strtol(tokens[i], NULL, 16);
		if((ch>31 && ch<128) || (ch<14 && ch>7)) //allow only printable characters
		{
			if(i==54)	//data starts from token no. 54
				fprintf(fp_info, "\n\n");
			n = (char)ch;
			fprintf(fp_info, "%c", n);
			invalidchar_flag=0;
		}
	}
	if(invalidchar_flag == 1)
		fprintf(fp_info, "NO DATA FOUND");
}

void print_summary(int total_packets, FILE* fp_info, char filename[])
{
	//used to print PCAP file summary 
	//input : total number of packets
	//output : many summary stats like avg packet size, transfer speed, etc 
	fprintf(fp_info, "|****************************************************************************************************|\n|*																									*|\n|*						SUMMARY FOR \"%s\" FILE                  					*|\n|*																									*|\n|****************************************************************************************************|\n\n", filename);	
	//fprintf(fp_info, "\n\n=========================== PCAP FILE SUMMARY ===========================\n");
	fprintf(fp_info, "\nPCAP Filename = %s\n", filename);	
	fprintf(fp_info, "\nTotal No. Of Packets = %d\n", total_packets);
	fprintf(fp_info, "\nTotal Time Span = %lu sec\n", sec_diff);
	fprintf(fp_info, "\nAverage packets/sec = %lu\n", (unsigned long)total_packets/sec_diff);
	fprintf(fp_info, "\nTotal bytes transferred = %lu\n", (unsigned long)total_size);
	fprintf(fp_info, "\nAverage packet size = %lu bytes\n", (unsigned long)total_size/total_packets);
	fprintf(fp_info, "\nAverage bytes/sec = %lu\n", (unsigned long)total_size/sec_diff);
	fprintf(fp_info, "\nAverage KBit/sec = %lu\n", (total_size/sec_diff)*8/1024);				//bytes per sec * 8/1024
	fprintf(fp_info, "\n=======================================================================================================\n");
}

/*
FOR REFERENCE : 

Packet No. 1 from "tcp-ecn-sample.pcap" is represented as follows in ic.txt (intermediate HEX form):

c0 01 14 7c 00 01 c0 02 12 68 00 00 08 00 45 00 00 2c 76 45 00 00 ff 06 20 81 01 01 17 03 01 01 0c 01 b5 dd 00 50 0a af 60 4e 00 00 00 00 60 c2 10 20 44 b2 00 00 02 04 02 18 00 00 2011-4-22 18:23:49.238

Its interpretation used in the code above is as follows:

------------------IP HEADER----------------------------
Token no.	Value in Packet 1		Field Name	

0-5			c0 01 14 7c 00 01 		Ethernet SRC Address
6-11		c0 02 12 68 00 00 		Ethernet DEST Address
12-13		08 00 			  		Type of packet (Eg: 08 00 = IP)						  
14			45				  		Header length in HEX
15			00					  	Unknown
16-17		00 2c 			  		Total Packet Length
18-19		76 45			  		Identification
20-21		00 00 			  		Fragment Offset
22			ff 				  		TTL (Time To Live of packet)
23			06				  		Transport Layer Protocol (Eg: 06 = TCP)
24-25		20 81 			  		Header Checksum
26-29		01 01 17 03  	  		SRC IP Address
30-33		01 01 0c 01				DEST IP Address

------------------TCP HEADER----------------------------
Token no.	Value in Packet 1		Field Name

34-35		b5 dd			  		TCP src port							
36-37		00 50 			  		TCP dest port					
38-41		0a af 60 4e 	  		Sequence Number				
42-45		00 00 00 00 	  		ACK Number 
46			60 				  		TCP Header Length
47			c2 				  		Flags Byte
48-49		10 20 			  		Window Size
50-51		44 b2 			  		Checksum
52-53		00 00			  		Unknown/Seperator from data

-Groups following the above groups contain data

-End of packet contains Timestamp of packet capture in our ic.txt, obtained from respective packet headers in epoch time format.
*/
